[theme]
base="dark"
primaryColor="#008fc4"  # Azul claro para elementos interactivos
backgroundColor="#003041"  # Azul oscuro para el fondo principal
secondaryBackgroundColor="#ff0202"  # Rojo para acentos y elementos secundarios
textColor="#fcfdff"  # Blanco ligeramente azulado para el texto principal
font="sans serif"

[theme.fonts]
heading = "Arial, sans-serif"
base = "Arial, sans-serif"
code = "Monospace"